### ISSUE TITLE
Patch: fixes error when too few books to download

### ISSUE THREAD

**Issue by AdamGleave** [nimiq/gutenberg-bulk-downloader#1]
Hi,

Thanks for building this tool, it saved me a lot of time! Came across a minor issue: if the number of books you're downloading exceeds the total number of books available given the filter criterion, then the app fails. Example (language 'ar' Arabic has only a single ebook in Gutenberg):
[adam@kestrel gutenberg-bulk-downloader]$ python3 manage.py --file-type txt --lang ar --n-ebooks 100
START.
- File types: ['txt']
- Number of ebooks to download: 100
- Language: ['ar']
- Initial url: http://www.gutenberg.org/robot/harvest?&filetypes[]=txt&langs[]=ar

Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    main(args)
  File "manage.py", line 16, in main
    crawler.run()
  File "/home/adam/dev/tmp/gutenberg-bulk-downloader/downloader/crawler.py", line 26, in run
    next_url = self._parse(r.content.decode('utf-8'))
  File "/home/adam/dev/tmp/gutenberg-bulk-downloader/downloader/crawler.py", line 51, in _parse
    link = p.a.get('href')
AttributeError: 'NoneType' object has no attribute 'get'

Patch below fixes this:
--- a/downloader/crawler.py
+++ b/downloader/crawler.py
@@ -48,17 +48,18 @@ class GutenbergCrawler:
         soup = BeautifulSoup(html)
         next_url = None
         for p in soup.find_all('p'):
-            link = p.a.get('href')
-            if p.a.text.lower() == 'next page':
-                next_url = 'http://www.gutenberg.org/robot/{}'.format(link)
-                continue
-            self.download_urls.append(link)
-            try:
-                self._check_n_ebooks()
-            except ThresholdReached:
-                return None
-            if p.a:
-                link = p.a.get('href')
-                if p.a.text.lower() == 'next page':
-                    next_url = 'http://www.gutenberg.org/robot/{}'.format(link)
-                    continue
-                self.download_urls.append(link)
-                try:
-                    self._check_n_ebooks()
-                except ThresholdReached:
-                    return None

**Comment by puntonim** [comment]
Oh great catch! And thank you for contributing. If you feel like opening a pull request I will merge.
